#!/system/bin/sh

# Governor
echo "conservative" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

# Min CPU OC
# Default is 300000
# You can set one: 
# 200000, 300000, 600000, 800000, 1008000, 1200000, 1350000
echo "300000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq

# Max CPU OC
# Default is 1008000
# You can set one: 
# 200000, 300000, 600000, 800000, 1008000, 1200000, 1350000
echo "1008000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq

# Min CPU screen off OC
# Default is 300000
# You can set one: 
# 200000, 300000, 600000, 800000, 1008000, 1200000, 1350000
echo "300000" > /sys/devices/system/cpu/cpu0/cpufreq/screen_off_max_freq

# Voltage for OC
echo "1365 1355 1345 1280 1155 980 940" > /sys/class/misc/customvoltage/mpu_voltages

# Voltage for GPU
echo "1230 1110 940" > /sys/class/misc/customvoltage/core_voltages

# Voltage for IVA
echo "1281 1104 940" > /sys/class/misc/customvoltage/iva_voltages

# Low memory killer
# This settings will be more agressive, but we 
# need it because our phone has only 200-300 mb free
# on lollipop. Delete this command if you want
# better multitasking, but worse performance
echo "2560,5120,25600,35840,46080,51200" > /sys/module/lowmemorykiller/parameters/minfree
